.TH MARK 1 "January 2017" "pass-import"

.SH NAME
pass import - A generic importer extension for the standard unix password
manager \fIpass\fP(1).


.SH SYNOPSIS
\fBpass import\fP <importer> [args]

.SH DESCRIPTION
\fBpass import\fP is a small password store extension allowing you to
conveniently import your password database to a password store repository.


.SH SUPPORTED IMPORTERS

.TP
\fB1password\fP
Reads files exported from 1Password and imports them into pass. Supports comma
and tab delimited text files, as well as logins (but not other items) stored
in the 1Password Interchange File (1PIF) format.

Supports using the title (default) or URL as pass-name, depending on your
preferred organization. Also supports importing metadata, adding them with
\fBpass insert --multiline\fP; the username and URL are compatible with
https://github.com/jvenant/passff.

.TP
\fBfpm\fP [\fI--help\fP] [\fI--man\fP] <xml>
Imports an .xml exported by \fBfpm2\fP into \fBpass\fP.


.TP
\fBgorrilla\fP

.TP
\fBkedpm\fP


.TP
\fBkeepass\fP export.xml
This script can handle duplicates and will merge them. Besides the password, the
fields \fI"UserName"\fP, \fI"URL"\fP and \fI"Notes"\fP (comment) will be inserted.
You get a warning if an entry has no password, but it will still insert it.

\fIUsage:\fP
.br
By default, takes the name of the root element and puts all passwords in there,
but you can disable this:
.br
\fBpass import keepass\fP -f export.xml -r ""
.br
Or you can use another root folder:
.br
\fBpass import keepass\fP -f export.xml -r foo


.TP
\fBkeepass2csv\fP
KeePassX 2+ on Mac allows export to CSV. The CSV contains the following headers :
\fI"Group"\fP, \fI"Title"\fP, \fI"Username"\fP, \fI"Password"\fP, \fI"URL"\fP,
\fI"Notes"\fP. Group and Title are used to build the path.
Password is the first line and the url and the notes are appended after

\fIUsage:\fP
.br
\fBpass import keepass2csv\fP <csv>



.TP
\fBkeepassx\fP

.TP
\fBkwallet\fP

.TP
\fBlastpass\fP
Reads CSV files exported from LastPass and imports them into pass.

Usage:
Go to lastpass.com and sign in. Next click on your username in the top-right
corner. In the drop-down meny that appears, click \fI"Export"\fP. After filling in
your details again, copy the text and save it somewhere on your disk. Make sure
you copy the whole thing, and resist the temptation to \fI"Save Page As"\fP - the
script doesn't like HTML.

Fire up a terminal and run the script, passing the file you saved as an argument.
It should look something like this:

\fBpass import lastpass\fP <path/to/passwords_file.csv>


.TP
\fBpassword-exporter\fP
Import password(s) exported by Password Exporter for Firefox in
csv format to pass format. Supports Password Exporter format 1.1.

Check the first line of your exported file. It must start with:

        # Generated by Password Exporter; Export format 1.1;

Support obfuscated export (wrongly called encrypted by Password Exporter).

It should help you to migrate from the default Firefox password
store to passff.

Please note that Password Exporter or passff may have problem with
fields containing characters like " or :.

More info at:
.br
<https://addons.mozilla.org/en-US/firefox/addon/password-exporter>
.br
<https://addons.mozilla.org/en-US/firefox/addon/passff>


.TP
\fBpwsafe\fP

.TP
\fBrevelation\fP

.TP
\fBroboform\fP
Save roboform print lists (like File > Print lists > Logins) to ~/roboform_print_lists.
.br
Run import: \fBpass import roboform\fP ~/roboform_print_lists

.SH SEE ALSO
.BR pass (1),


.SH AUTHORS
.B pass import
was written by
.MT alexandre@pujol.io
Alexandre Pujol
.ME .

.B 1Password
importer script was written by
.MT tobias@langhoff.no
Tobias V. Langhoff
.ME .

.B fpm
importer script was written by
.MT jeffrey.ratcliffe@gmail.com
Jeffrey Ratcliffe
.ME .

.B gorilla
importer script was written by
.MT david.sklar@gmail.com
David Sklar
.ME .

.B kedpm
importer script was written by
.MT anarcat@orangeseeds.org
Antoine Beaupré
.ME .

.B keepass2csv
importer script was written by
.MT dfrancoeur04@gmail.com
David Francoeur
.ME .

.B keepass
importer script was written by
.MT stefan.simroth@gmail.com
Stefan Simroth
.ME .

.B keepassx
importer script was written by
.MT iiska@iki.fi
Juhamatti Niemelä
.ME .

.B kwallet
importer script was written by
.MT iiska@iki.fi
Juhamatti Niemelä
.ME
and by
.MT diggory.hardy@gmail.com
Diggory Hardy
.ME .

.B lastpass
importer script was written by
.MT alex.sayers@gmail.com
Alex Sayers
.ME .

.B password-exporter
importer script was written by
.MT daniele.pizzolli@create-net.org
Daniele Pizzolli
.ME .

.B pwsafe
importer script was written by
.MT tom@whyscream.net
Tom Hendrikx
.ME .

.B revelation
importer script was written by
.MT em@nerd.ocracy.org
Emanuele Aina
.ME
and by
Toni Corvera

.B roboform
importer script was written by
.MT sergey@makridenkov.com
Sergey Makridenkov
.ME .

The importers script are under they own license.

.SH COPYING
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
